### ISSUE TITLE
Android register does not check emails

### ISSUE THREAD

**Issue by artemking4** [principia-preservation-project/principia-web#12]
https://github.com/principia-preservation-project/principia-web/blob/master/internal/android_register.php
Doesnt check if the mail is already taken/is invalid.

**Comment by rollerozxa** [comment]
Yeah, right now there's no checks whatsoever for the email field. Not really a problem since it isn't really used for anything, should be fairly easy to implement though.

**Comment by rollerozxa** [comment]
Fixed in b745d08.
