### ISSUE TITLE
Invalid format string in level getting code

### ISSUE THREAD

**Issue by artemking4** [principia-preservation-project/principia-web#13]
we have
```$levelpath = sprintf('somepath/%s.plvl', $level);```
it should be
```$levelpath = sprintf('somepath/%d.plvl', $level);```
because $level is always an int (or null, but in this case you should return internal/null.plvl)

**Comment by rollerozxa** [comment]
This wouldn't really be a problem since it already converts it into an int in the previous line... But, fixed in 122380c.
